apiVersion: batch/v1
kind: Job
metadata:
  name: hackernews-collectstatic
spec:
  template:
    metadata:
      name: hackernews-collectstatic
    spec:
      containers:
      - name: hackernews-collectstatic
        image: gcr.io/playground-223020/hackernews:latest
        imagePullPolicy: Always
        env:
        - name: ENV
          value: "production"
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: STATICFILES_STORAGE
          value: "storages.backends.gcloud.GoogleCloudStorage"
        - name: DEFAULT_FILE_STORAGE
          value: "storages.backends.gcloud.GoogleCloudStorage"
        - name: SECRET_KEY
          value: # ADD HERE YOUR SECRET KEY
        - name: DATABASE_URL
          value: # ADD HERE YOUR DATABASE URL
        - name: GS_ACCESS_KEY_ID
          value: # ADD HERE YOUR GS ACCESS KEY ID
        - name: GS_SECRET_ACCESS_KEY
          value: # ADD HERE YOUR GS SECRET ACCESS KEY
        - name: GS_BUCKET_NAME
          value: # ADD HERE YOUR GS BUCKET NAME
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: # ADD HERE YOUR CREDENTIALS FILE NAME
        command: [ "/bin/sh", "-c", "python manage.py collectstatic --noinput" ]
      restartPolicy: Never
