apiVersion: v1
kind: Service
metadata:
  name: hackernews-lb
  labels:
    app: hackernews
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: hackernews
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hackernews-deployment
  labels:
    app: hackernews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackernews
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hackernews
    spec:
      containers:
      - name: web
        imagePullPolicy: Always
        image: gcr.io/playground-223020/hackernews:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "production"
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: STATICFILES_STORAGE
          value: "storages.backends.gcloud.GoogleCloudStorage"
        - name: DEFAULT_FILE_STORAGE
          value: "storages.backends.gcloud.GoogleCloudStorage"
        - name: SECRET_KEY
          value: # ADD HERE YOUR SECRET KEY
        - name: DATABASE_URL
          value: # ADD HERE YOUR DATABASE URL
        - name: GS_ACCESS_KEY_ID
          value: # ADD HERE YOUR GS ACCESS KEY ID
        - name: GS_SECRET_ACCESS_KEY
          value: # ADD HERE YOUR GS SECRET ACCESS KEY
        - name: GS_BUCKET_NAME
          value: # ADD HERE YOUR GS BUCKET NAME
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: # ADD HERE YOUR CREDENTIALS FILE NAME
