apiVersion: batch/v1
kind: Job
metadata:
  name: hackernews-migrate
spec:
  template:
    metadata:
      name: hackernews-migrate
    spec:
      containers:
      - name: hackernews-migrate
        image: gcr.io/playground-223020/hackernews:latest
        imagePullPolicy: Always
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: hackernews-config
              key: hackernews.env
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: hackernews-config
              key: hackernews.debug
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: hackernews-config
              key: hackernews.allowed_hosts
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: hackernews-config
              key: hackernews.secret_key
      restartPolicy: Never
