apiVersion: v1
kind: Secret
metadata:
  name: hackernews-secrets
type: Opaque
data:
  hackernews.secret_key: ""
  hackernews.database_url: ""
  hackernews.gs_access_key_id: ""
  hackernews.gs_secret_access_key: ""
  hackernews.gs_bucket_name: ""
  hackernews.google_application_credentials: ""
